USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PIPELINE_WH;
USE DATABASE PIPELINE_DB;
USE SCHEMA BRONZE;

DROP TABLE IF EXISTS RAW_CSV_EVENTS;

CREATE TABLE RAW_CSV_EVENTS (
  event_id   STRING,
  event_time TIMESTAMP_NTZ,
  user_id    NUMBER,
  event_type STRING,
  value      NUMBER
);

DROP FILE FORMAT IF EXISTS CSV_EVENTS_FF;

CREATE FILE FORMAT CSV_EVENTS_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  NULL_IF = ('NULL', 'null');

DROP STAGE IF EXISTS CSV_EVENTS_STAGE;

CREATE STAGE CSV_EVENTS_STAGE
  FILE_FORMAT = CSV_EVENTS_FF;