USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PIPELINE_WH;
USE DATABASE PIPELINE_DB;
USE SCHEMA BRONZE;

-- JSONL file format for API events
DROP FILE FORMAT IF EXISTS API_EVENTS_JSON_FF;

CREATE FILE FORMAT API_EVENTS_JSON_FF
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

-- Stage for API events 
DROP STAGE IF EXISTS API_EVENTS_STAGE;

CREATE STAGE API_EVENTS_STAGE
  FILE_FORMAT = API_EVENTS_JSON_FF;